Web styles
Nevadyaasha/landing_page pull request #2
Opened 2024-04-16 10:35 UTC by Nevadyaasha

2024-04-18 20:28 UTC, EugenNekrasov commented
Давай, добавим фавиконку. Зачем:
- на десктопе у вкладки нет отличительного признака
- браузер автоматически пытается подгрузить иконку, не находит, получает 404 ошибку
- иконок ожидают и работодатели при просмотре портфолио

2024-04-18 20:33 UTC, EugenNekrasov commented
Кнопкам и ссылкам при наведении просится подсветка фоном, подчёркиванием или цветом букв. Это ожидаемое поведение на других сайтах. Почитай про [закон Якобсона](https://lawsofux.com/jakobs-law/).

2024-04-18 20:39 UTC, EugenNekrasov requested changes

2024-04-18 20:39 UTC, runtime-exceptional commented on mobilestyles.css
> +#menuid:checked~.menu {
Прежний вариант лучше читается. Предлагаю оставить его.

2024-04-18 20:39 UTC, runtime-exceptional commented on mobilestyles.css
> +.nav-accordion__list-item .link {
Напомни пожалуйста, почему так решили? Без контекста кажется серъёзным нарушением БЭМ - один блок зависит от _элемента_ другого блока.

2024-04-18 20:39 UTC, runtime-exceptional commented on mobilestyles.css
>  .list__item .link {
Здесь тот же вопрос, что и выше.

2024-04-18 20:39 UTC, runtime-exceptional commented on desktopstyles.css
> +    .growth-monitoring__learn-more {
Этот селектор (как и в 62-64 строках) можно приятно упростить: `.feature > * { ... }` По-человечески будет "все прямые потомки блока .feature". Чем это лучше:
- меньше кода
- если изменится состав блоков, не надо дописывать сюда
- ответственность за размеры переходит универсальному блоку `.feature`. Так ты позволяешь блокам sales-monitoring, customer-support и growth-monitoring сосредоточиться на цветах и композиции, которые отличаются во всех из них.

2024-04-18 20:39 UTC, runtime-exceptional commented on desktopstyles.css
> +    .links__list-item .link {
Триггерюсь на зависимость блоков друг от друга.

2024-04-18 20:39 UTC, runtime-exceptional commented on desktopstyles.css
> +        font-weight: 400;
Триггерюсь на зависимость блоков друг от друга.

2024-04-18 20:39 UTC, EugenNekrasov commented on desktopstyles.css
> +        font-size: 18px;
Понимаю, почему такой шрифт у элементов блоков link и cta. Не понимаю, за что досталось фиолетовой кнопке) Давай обсудим, может, модификатор другой придумаем.

2024-04-18 20:39 UTC, EugenNekrasov commented on desktopstyles.css
> +    .feature .growth-monitoring {
Этот селектор не найдёт искомого блока. `feature` и `growth-monitoring` лежат на одном dom-элементе, а селектор ищет второй _внутри_ первого. Попробуй убрать пробел и свериться с макетом.

2024-04-18 20:39 UTC, EugenNekrasov commented on desktopstyles.css
> +    .growth-monitoring__pretitle {
Вот тут возникает сомнение - а не должны ли эти общие стили быть в элементах блока feature? Тогда у feature был бы обширный набор элементов со стилями ниже. Если элемент надо перекрасить, подвинуть, то навешиваются модификаторы sales-monitoring, customer-support, growth-monitoring.
Плюсы:
- меньше кода
- вся ответственность на универсальном блоке feature

Минусы:
- не придумал, накидай плз. Может, в глаза долблюсь)

2024-04-18 20:39 UTC, EugenNekrasov commented on mobilestyles.css
> +.testimonials_reviews-viewport {
По БЭМу этот селектор означает "у блока testimonials модификатор reviews-viewport". Модификатор весится на блок или элемент. Он их модифицирует. Однако этот класс - единственный на dom-элементе. Кажется, здесь имелся в виду _элемент_ reviews-viewport. Тогда селектор примет вид `.testimonials_reviews-viewport`.

2024-04-22 14:03 UTC, Nevadyaasha commented on mobilestyles.css
> +.nav-accordion__list-item .link {
Потому что текст внутри link, а внутри li - только анкор, стили не применялись в итоге.

2024-04-22 14:04 UTC, Nevadyaasha commented on desktopstyles.css
> +    .growth-monitoring__learn-more {
А это можно применить к двум предыдущим БЭМ-нарушениям с link?

2024-04-22 14:07 UTC, Nevadyaasha commented on desktopstyles.css
> +    .growth-monitoring__pretitle {
Там все равно разные цвета. Можно было бы решить вопрос с помощью 1-3child, но кажется, что кода столько же.

2024-04-22 14:08 UTC, Nevadyaasha commented on mobilestyles.css
> +.testimonials_reviews-viewport {
Не поняла, в чем разница?

2024-04-22 17:12 UTC, Nevadyaasha commented on desktopstyles.css
> +        font-size: 18px;
Проблема: модификатор размера шрифта а не фиолетовости, заменила на hero__go-trial. Дальше продумать общий модификатор для всех кнопок: их 2.

2024-04-24 13:36 UTC, Nevadyaasha commented on desktopstyles.css
> +    .links__list-item .link {
довесила класс footer-navigation__link и поменяла на него

2024-04-24 13:36 UTC, Nevadyaasha commented on desktopstyles.css
> +        font-weight: 400;
Тоже что и выше: 
.footer-navigation__link:first-child

2024-04-24 13:38 UTC, Nevadyaasha commented on mobilestyles.css
> +.nav-accordion__list-item .link {
Запилила новый класс nav-accordion__link и заменила на него

2024-04-24 14:13 UTC, Nevadyaasha commented on mobilestyles.css
>  .list__item .link {
пофиксила

2024-04-24 15:22 UTC, Nevadyaasha commented on desktopstyles.css
> +    .growth-monitoring__learn-more {
было больно, но я смогла

2024-04-25 19:53 UTC, EugenNekrasov requested changes

2024-04-25 19:53 UTC, EugenNekrasov commented on desktopstyles.css
> +summary.faq-accordion__question:hover {
```suggestion
.faq-accordion__question:hover {
```

2024-04-25 19:53 UTC, EugenNekrasov commented on mobilestyles.css
>      margin-bottom: 56px;
То же самое написано в 212 строчке. Надо удалить код либо тут, либо там.

2024-04-25 19:53 UTC, EugenNekrasov commented on mobilestyles.css
>      display: block;
Этот элемент вложен в блок `.feature`, который является флексом. Поэтому свойство `display` у дочерних блоков флекса игнорируются. Предлагаю снести.

2024-04-25 20:16 UTC, EugenNekrasov requested changes
У всех аккордеонов в десктоп сафари есть свои маркеры слева. Надо их убрать. Возьми мой комп для отладки. Заодно, проверь, как с телефона в сафари будет выглядеть.
<img width="631" alt="image" src="https://github.com/Nevadyaasha/landing_page/assets/16029858/bfd8fdb3-3089-4b43-86aa-34d3dbf384e8">

2024-04-25 20:16 UTC, EugenNekrasov commented on mobilestyles.css
> +.footer-navigation__links_desktop {
Этот селектор не работает, ведь после рефача `links-desktop` стал цельным элементом, а элементом с модификатором. Поэтому ссылки десктопа сейчас отображаются на мобилке.

2024-04-25 20:16 UTC, EugenNekrasov commented on mobilestyles.css
>      color: #EB2891;
Цвет кнопок по умолчанию в браузерах разный. В сафари он откровенно серый. Лучше задай его явно.

2024-04-25 20:19 UTC, EugenNekrasov commented on mobilestyles.css
> +.testimonials_reviews-viewport {
Точно, одно подчёркивание добавил в последней строчке)

2024-04-25 20:49 UTC, EugenNekrasov requested changes

2024-04-25 20:49 UTC, EugenNekrasov commented on mobilestyles.css
> +    flex-grow: 1;
`flex-grow` работает лишь на дочерних элементах флекса.

2024-04-25 20:49 UTC, EugenNekrasov commented on desktopstyles.css
> +        background-repeat: no-repeat;
7 свойств отсюда идентичны тем, что применяются из мобильных стилей

2024-04-25 20:49 UTC, EugenNekrasov commented on mobilestyles.css
> +.hero__trusted-description {
Обрати внимание, что этому элементу задаётся `display: block`, хотя это итак блочный элемент (в вёрстке это `<p>`).

2024-04-25 20:49 UTC, EugenNekrasov commented on mobilestyles.css
> +    margin-left: auto;
Это свойство лишнее, т.к. оно продублировано в 463 строке.

2024-04-25 20:49 UTC, EugenNekrasov commented on desktopstyles.css
> +    .tariff__price {
В десктопном сафари этот блок уехал.

2024-04-26 12:26 UTC, Nevadyaasha commented on mobilestyles.css
>      margin-bottom: 56px;
Не нашла такого в 315 строчке и рядом, вероятно уже снесено позднее

2024-04-27 09:59 UTC, EugenNekrasov commented on mobilestyles.css
>      margin-bottom: 56px;
315 это старая строчка. После изменений она стала 283.

2024-04-28 08:59 UTC, EugenNekrasov approved these changes

2024-04-28 09:05 UTC, merged